import "./globals.css";

import type { Metadata } from "next";
import { fontSans } from "@/lib/fonts";
import clsx from "clsx";
import Providers from "@/components/providers";
import TailwindIndicator from "@/components/tailwind-indicator";
import SiteHeader from "@/components/site-header";
import { Toaster } from "@/components/ui/toaster";
import SiteFooter from "@/components/site-footer";

export const metadata: Metadata = {
  title: "Microtube",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={clsx(
          "min-h-screen bg-background antialiased",
          fontSans.className
        )}
      >
        <Providers>
          <div className="relative flex min-h-screen flex-col">
            <SiteHeader />
            <div className="flex-1 container py-4 md:py-8">{children}</div>
            <SiteFooter />
          </div>
        </Providers>
        <TailwindIndicator />
        <Toaster />
      </body>
    </html>
  );
}
